version: '3'

services:
  master:
    container_name: "${COMPOSE_PROJECT_NAME:-citus}_master"
    image: "citusdata/citus:12.0.0"
    ports:
      - "${COORDINATOR_EXTERNAL_PORT:-5432}:5432"
    labels:
      - "com.citusdata.role=Master"
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dbt-project
      - PGUSER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - postgres-network
    volumes:
      - ./citus-db-data/:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  worker:
    image: "citusdata/citus:12.0.0"
    labels:
      - "com.citusdata.role=Worker"
    depends_on:
      - manager
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dbt-project
      - PGUSER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    command: "/wait-for-manager.sh"
    volumes:
      - ./citus-healthcheck:/healthcheck

  manager:
    container_name: "${COMPOSE_PROJECT_NAME:-citus}_manager"
    image: "citusdata/membership-manager:0.3.0"
    volumes:
      - "${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock"
      - ./citus-healthcheck:/healthcheck
    depends_on:
      - master
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dbt-project

  metabase:
    image: metabase/metabase
    ports:
      - "3000:3000"
    environment:
      - MB_DB_FILE=/metabase.db

  postgresql:
    image: postgres:15.2
    hostname: postgresql
    container_name: postgresql
    restart: unless-stopped
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=ingestion_data      
      - PGUSER=user
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5443:5432"
    networks:
      - postgres-network

networks: 
  postgres-network:
    driver: bridge
