dbt_project:
  outputs:
    dev:
      dbname: dbt-project
      host: localhost
      pass: pass
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: user
  target: dev
