my_project:
  outputs:
    dev:
      dbname: dbt-project
      host: localhost
      pass: pass
      port: 5433
      schema: public
      threads: 1
      type: postgres
      user: postgres
  target: dev
