version: "3.8"

networks:
  data_platform:

services:
  #############################################################################
  # POSTGRE
  #############################################################################

  postgresql:
    image: postgres:15.2
    hostname: postgresql
    container_name: postgresql
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: ingestion_data
    volumes:
    - ./postgres-data:/var/lib/postgresql/data
    ports:
    - 5443:5432
    networks:
    - data_platform